### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by matusca96** [thamudi/psychonauts-api#3]
Hello @thamudi, first of all thanks for this great api!

A while ago I've created a frontend project based on this api, but by checking these days, I saw that isn't working anymore. Can you check what is going on?

![image](https://github.com/thamudi/psychonauts-api/assets/24362309/a5059f54-cbcb-49c0-b36e-110873122986)

**Comment by thamudi** [comment]
Yup. I am in the process of updating the app. Should be done by the end of the week

**Comment by thamudi** [comment]
Hey @matusca96 Sorry for taking forever. Been busy with other projects.
I finally got around fixing the API and migrating from Heroku to vercel.
You can find the new Link in the project.
[New psychonauts api](https://psychonauts-api.vercel.app/).
